version: "3"
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - fp_network

  mongo-express:
    image: mongo-express
    container_name: "mongo-express"
    restart: always
    ports:
      - 8081:8081
    networks:
      - fp_network
    depends_on:
      - mongo

  backend:
    build: Backend
    environment:
    - ENV=${ENV}
    - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    - S3_KEY=${S3_KEY}
    - S3_SECRET=${S3_SECRET}
    - APP_SECRET=${APP_SECRET}
    - S3_PP_URL=${S3_PP_URL}
    container_name: backend
    ports:
      - 5000:5000
    volumes:
      - "./Backend:/app"
    networks:
      - fp_network
networks:
  fp_network:
    driver: bridge
